# Generated by Django 5.2 on 2025-04-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0003_remove_historicaltag_history_user_and_more'),
        ('users', '0002_customgroup_alter_user_groups_historicalcustomgroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_tags', to='extras.tag', verbose_name='Теги'),
        ),
    ]
