# Generated by Django 5.2 on 2025-04-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='last_name2',
            field=models.CharField(max_length=50, null=True, verbose_name='Фамилия2'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name2',
            field=models.CharField(max_length=50, null=True, verbose_name='Фамилия2'),
        ),
    ]
