# Generated by Django 5.2 on 2025-05-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_historicalpasswordresetrequest_passwordresetrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordresetrequest',
            options={'verbose_name': 'запрос на смену пароля', 'verbose_name_plural': 'заявки на смену пароля'},
        ),
        migrations.RemoveField(
            model_name='passwordresetrequest',
            name='user',
        ),
        migrations.AddField(
            model_name='passwordresetrequest',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Электронная почта'),
        ),
        migrations.DeleteModel(
            name='HistoricalPasswordResetRequest',
        ),
    ]
