# Generated by Django 5.2 on 2025-04-06 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_historicaluser_last_name2_user_last_name2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='last_name2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tags',
        ),
    ]
