version: '3.8'

services:
  web:
    build: .
    container_name: netscope
    command: uvicorn NetScope.asgi:application --host 0.0.0.0 --port 8000 --reload
    environment:
      - DJANGO_SETTINGS_MODULE=NetScope.settings
      - WATCHFILES_FORCE_POLLING=true
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: netscope_db
    environment:
      POSTGRES_DB: netscope
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - db
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"


volumes:
  pgdata:
  pgadmin_data:
