# Generated by Django 5.2 on 2025-04-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0002_historicalcustomfield_historicaltag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltag',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='taggeditem',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='taggeditem',
            name='tag',
        ),
        migrations.AlterModelOptions(
            name='customfield',
            options={'verbose_name': 'Кастомное поле', 'verbose_name_plural': 'Кастомные поля'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.RemoveField(
            model_name='customfield',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='customfield',
            name='object_id',
        ),
        migrations.AddField(
            model_name='customfield',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_tags', to='extras.tag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='field_type',
            field=models.CharField(choices=[('char', 'CharField'), ('int', 'IntegerField'), ('date', 'DateField'), ('boolean', 'BooleanField')], max_length=10, verbose_name='Тип данных'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название поля'),
        ),
        migrations.DeleteModel(
            name='HistoricalCustomField',
        ),
        migrations.DeleteModel(
            name='HistoricalTag',
        ),
        migrations.DeleteModel(
            name='TaggedItem',
        ),
    ]
