# Generated by Django 5.2 on 2025-04-06 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0004_alter_customfield_options_alter_tag_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='tags',
        ),
    ]
