# Generated by Django 5.2 on 2025-05-05 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_roleicon_file_roleicon_file_name_and_more'),
        ('topology', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapDevicePlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.device')),
                ('network_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='topology.networkmap')),
            ],
            options={
                'unique_together': {('network_map', 'device')},
            },
        ),
    ]
