# Generated by Django 5.2 on 2025-05-03 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Файл SVG, PNG, EPS или WEBP, который будет отображаться вместо автоматической иконки', upload_to='icons/roles/', verbose_name='Файл иконки')),
                ('role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='icon', to='inventory.devicerole', verbose_name='Роль устройства')),
            ],
            options={
                'verbose_name': 'иконка роли',
                'verbose_name_plural': 'иконки ролей',
            },
        ),
    ]
