# Generated by Django 5.2 on 2025-05-03 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_roleicon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roleicon',
            name='role',
        ),
        migrations.AddField(
            model_name='roleicon',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='icons', to='inventory.devicerole', verbose_name='Роли'),
        ),
    ]
