# Generated by Django 5.2 on 2025-05-03 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_roleicon_role_roleicon_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roleicon',
            name='file',
        ),
        migrations.AddField(
            model_name='roleicon',
            name='file_name',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Файл иконки'),
        ),
        migrations.AlterField(
            model_name='roleicon',
            name='roles',
            field=models.ManyToManyField(related_name='assigned_icons', to='inventory.devicerole', verbose_name='Назначенные роли'),
        ),
    ]
