# Generated by Django 5.2 on 2025-06-15 19:42

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0004_remove_roleicon_file_roleicon_file_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, verbose_name='Имя пользователя')),
                ('password', models.CharField(max_length=128, verbose_name='Пароль')),
                ('ip', models.GenericIPAddressField(verbose_name='IP-адрес для SSH')),
                ('port', models.IntegerField(default=22, verbose_name='Порт')),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access', to='inventory.device')),
            ],
            options={
                'verbose_name': 'доступ к устройству',
                'verbose_name_plural': 'доступы к устройствам',
            },
        ),
        migrations.CreateModel(
            name='HistoricalDeviceAccess',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('username', models.CharField(max_length=64, verbose_name='Имя пользователя')),
                ('password', models.CharField(max_length=128, verbose_name='Пароль')),
                ('ip', models.GenericIPAddressField(verbose_name='IP-адрес для SSH')),
                ('port', models.IntegerField(default=22, verbose_name='Порт')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('device', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.device')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical доступ к устройству',
                'verbose_name_plural': 'historical доступы к устройствам',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
